language: node_js
node_js:
  - 14.3.0
cache:
  directories:
    - "node_modules"
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
script:
  - npm run test